apiVersion: v2
name: welcome
description: Welcome app
type: application
version: "0.0.1"
appVersion: "v0.0.1"
kubeVersion: ">= 1.11.0-0"
keywords:
  - example
  - app
home: https://knela.dev
maintainers:
  - name: knelasevero
    email: lucassalves65@gmail.com
