on:
  repository_dispatch:
    types: [deploy]

env:
  # Common versions
  GO_VERSION: '1.17'
  GOLANGCI_VERSION: 'v1.33'
  DOCKER_BUILDX_VERSION: 'v0.4.2'
  KUBECONFIGCONTENT: ${{ secrets.KUBECONFIG }}
  GCLOUD: "true"
  GCP_SM_SA_GKE_JSON: ${{ secrets.GCP_SM_SA_GKE_JSON }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_GKE_CLUSTER: ${{ secrets.GCP_GKE_CLUSTER }}
  GCP_GKE_ZONE: ${{ secrets.GCP_GKE_ZONE }}

name: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch'
    steps:

      - name: Ref checkout
        uses: actions/checkout@v2
        with:
          ref: '${{ github.event.client_payload.ref }}'

      - name: Fetch History
        run: git fetch --prune --unshallow

      - uses: sigstore/cosign-installer@main

      - name: Write signing pub to disk (only needed for `cosign sign --pub`)
        run: echo "${{ secrets.VERIFY_KEY }}" > cosign.pub

      - name: Verify signature
        run: |
          cosign verify --key cosign.pub knelasevero/wecolme:${{ github.event.client_payload.tag }}
      
      # Can be ignored if not using gcloud, by just not setting GCLOUD (For local run for example)
      - name: Setup gcloud CLI
        if: env.GCLOUD == 'true'
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ env.GCP_SM_SA_GKE_JSON }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      # Can be ignored if not using gcloud, by just not setting GCLOUD (For local run for example)
      - name: Get the GKE credentials
        if: env.GCLOUD == 'true'
        run: |-
          gcloud container clusters get-credentials "$GCP_GKE_CLUSTER" --zone "$GCP_GKE_ZONE" --project "$GCP_PROJECT_ID"

      # ./deploy/scripts/write_kubeconfig.sh gets $KUBECONFIGCONTENT and writes to ~/.kube/config
      # only if the server is not configred yet
      - name: Deploy
        env:
          KUBECONFIG: /home/runner/.kube/config
        run: |
          make helm.build
          TAG=${{ github.event.client_payload.tag }} make deploy
